"""
Expected Object Counts Module

This module contains classes and functions for probabilistic segmentation 
and object counting from the expected_object_count_v01.ipynb notebook.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import math
import base64
import json
from torch.distributions.dirichlet import Dirichlet


# ============================================================================
# Probabilistic Segmentation Classes and Functions
# ============================================================================

class ProbabilisticSegmentation():
    def __init__(self, probability_map=None, dimensions=None, label_map = None):
        num_provided_args = sum([arg is not None for arg in [dimensions, probability_map, label_map]])
        if num_provided_args != 1:
            raise ValueError("Exactly one of 'dimensions', 'probability_map', or 'label_map' must be provided.")
        if dimensions is not None:
            self.K, self.H, self.W = dimensions
            self.probability_map = torch.ones(dimensions)/self.K 
        if probability_map is not None:
            self.check_probability_map(probability_map)
            self.K, self.H, self.W = probability_map.shape
            self.probability_map = probability_map
        if label_map is not None:
            self.probability_map = self.probability_map_from_label_map(label_map)
            self.check_probability_map()
            self.K, self.H, self.W = self.probability_map.shape

    def check_probability_map(self, probability_map=None):
        if probability_map is None:
            probability_map = self.probability_map
        if not (probability_map >= 0).all():
            raise ValueError("All values in 'probability_map' must be non-negative.")
        if not torch.isclose(probability_map.sum(dim=0), torch.ones(probability_map.shape[1], probability_map.shape[2], device = probability_map.device)).all():
            raise ValueError("The sum of probabilities along dimension 0 must be equal to 1 for each pixel.")
        else:
            print("Probability map is valid.")

    def probability_map_from_label_map(self, label_map):
        ##image dimensions
        H,W = label_map.shape
        ##find the unique labels
        unique_labels = torch.unique(label_map)
        K = len(unique_labels)
        probability_map = torch.zeros((K, H, W))
        for i,k in enumerate(unique_labels):
            probability_map[i] = (label_map == k) 
        return probability_map

    def pixel_comembership(self):
        pm = self.probability_map.flatten(1) ##K x HW
        return pm.T @ pm ##HW x HW

    def probability_map_to_string(self):
        """
        Converts a PyTorch tensor (probability map) into a portable JSON string.
        
        Args:
            tensor (Tensor): The input probability map.
            
        Returns:
            str: A JSON string containing shape, dtype, and base64-encoded data.
        """
        # 1. Move to CPU and convert to Numpy
        # We must detach if it requires grad, and move to CPU to convert to numpy
        np_array = self.probability_map.detach().cpu().numpy()
        
        # 2. Serialize the binary data
        # tobytes() gets the raw bits. b64encode converts those bits to ASCII bytes.
        # decode('utf-8') turns those ASCII bytes into a standard Python string.
        b64_data = base64.b64encode(np_array.tobytes()).decode('utf-8')
        
        # 3. Create a dictionary with necessary metadata
        # We need the dtype and shape to reconstruct it correctly later.
        payload = {
            "dtype": str(np_array.dtype),
            "shape": np_array.shape,
            "data": b64_data
        }
        
        # 4. Convert dictionary to JSON string
        return json.dumps(payload)


def dirichlet_probability_map(K, H, W, alpha=20.):
    alpha = torch.tensor([alpha]*K)
    dist = Dirichlet(alpha)
    probability_map = dist.sample((W,H)).transpose(0,2)
    return probability_map

    

def string_to_probability_map(s):
    """
    Reconstructs a PyTorch tensor from the string generated by `probability_map_to_string`.
    
    Args:
        s (str): The JSON string.
        
    Returns:
        Tensor: The reconstructed PyTorch tensor.
    """
    # 1. Parse the JSON string
    payload = json.loads(s)
    
    # 2. Extract metadata
    dtype_name = payload['dtype']
    shape = payload['shape']
    b64_data = payload['data']
    
    # 3. Decode the binary data
    # Convert string back to bytes
    raw_bytes = base64.b64decode(b64_data)
    
    # 4. Reconstruct Numpy Array
    # frombuffer interprets the raw bytes as numbers of the specified dtype
    np_array = np.frombuffer(raw_bytes, dtype=dtype_name)
    
    # 5. Reshape and Convert to Torch
    np_array = np_array.reshape(shape)
    
    # We create a copy to avoid "The given NumPy array is not writeable" warnings 
    # that can occur with read-only buffers from strings.
    tensor = torch.from_numpy(np_array.copy())
    
    return tensor    


# ============================================================================
# Object Counting Network
# ============================================================================

class ExpectedObjectCountNet(nn.Module):
    def __init__(self, probability_map):
        super(ExpectedObjectCountNet, self).__init__()
        self.probability_map = nn.Parameter(probability_map)
        self.K = self.probability_map.shape[0]
        self.H = self.probability_map.shape[1]
        self.W = self.probability_map.shape[2]
        
    def _expected_object_count(self, probes):
        '''
        probes: (B, H, W), B binary probes of size H x W
        '''
        B,H,W = probes.shape
        pseg = self.probability_map #(K, H, W)
        wpseg = torch.einsum('BHW, KHW->BKHW', probes, pseg) # (B, K, H, W)
        prob_seg_not_sampled = 1 - wpseg # (B, K, H, W)
        prob_never_picked = prob_seg_not_sampled.prod(dim=-1).prod(dim=-1) # (B, K)
        expected_object_count = torch.sum(1-prob_never_picked, dim=1) # (B)
        return expected_object_count 

    def forward(self, probes):
        return self._expected_object_count(probes)

    def train(self, probes, count_data, lr=10., laplacian_weight=5., spatial_concentration_weight=1., number_of_epochs=2000, print_progress=False):
        ##instantiate a loss function and optimizer
        from vseg.src.vseg.models import ExpGradient
        optimizer = ExpGradient(self.parameters(), lr=lr)
        criterion = nn.MSELoss(reduction='mean')
        lps = LaplacianSmoothnessLoss()
        var = SpatialConcentrationLoss()

        ##train the network, saving the loss history
        loss_history = []
        for epoch in range(number_of_epochs):
            optimizer.zero_grad()
            pred = self.forward(probes)
            loss = criterion(pred, count_data)
            energy = lps(self.probability_map[np.newaxis,...])
            fogginess = var(self.probability_map[np.newaxis,...])
            total_loss = loss*1. + energy*laplacian_weight + fogginess*spatial_concentration_weight
            loss_history.append(total_loss.item())
            total_loss.backward()
            optimizer.step()
            if print_progress:
                print(f'Epoch {epoch}, loss : {loss.item():.9f}, energy: {energy.item():.9f}, fogginess: {fogginess.item():.9f}')   
        if print_progress:
            print('Done')
        return loss_history

        

# ============================================================================
# Probe Generation 
# ============================================================================

import torch
import matplotlib.pyplot as plt


class ProbeSet:
    """
    Manages k-order probes across dual resolutions: a working resolution (H_work, W_work)
    and a display resolution (H_disp, W_disp).

    Guarantees exact value consistency by sampling pixel centers on the discrete working
    grid and mapping them to normalized coordinates [0, 1].
    """
    def __init__(self, H_work, W_work, H_disp, W_disp, N, order, device='cpu'):
        self.H_work = H_work
        self.W_work = W_work
        self.H_disp = H_disp
        self.W_disp = W_disp
        self.N = N
        self.order = order
        self.device = device

        num_pixels_work = H_work * W_work
        total_slots = N * order

        # Check image coverage flag relative to working resolution
        self.all_pixels_probed = total_slots > num_pixels_work

        # 1. Deck sampling on the working grid
        permuted_indices = torch.randperm(num_pixels_work, device=device)

        if total_slots <= num_pixels_work:
            all_indices = permuted_indices[:total_slots]
        else:
            num_fillers = total_slots - num_pixels_work
            filler_indices = torch.randint(0, num_pixels_work, (num_fillers,), device=device)
            all_indices = torch.cat([permuted_indices, filler_indices])
            all_indices = all_indices[torch.randperm(total_slots, device=device)]

        probe_indices = all_indices.view(N, order)

        # 2. Extract discrete working coordinates (row, col)
        self.y_work = probe_indices // W_work
        self.x_work = probe_indices % W_work

        # 3. Map pixel centers to normalized range [0, 1] using half-pixel offsets:
        # norm_coord = (index + 0.5) / size
        self.coords = torch.stack([
            (self.x_work.float() + 0.5) / W_work,
            (self.y_work.float() + 0.5) / H_work
        ], dim=-1)  # Shape: (N, order, 2)

        # 4. Initialize default masks for both resolutions
        self.working_masks = self.generate_masks(self.H_work, self.W_work)
        self.display_masks = self.generate_masks(self.H_disp, self.W_disp)

    def generate_masks(self, H=None, W=None):
        """
        Generates binary masks at any specified resolution (H, W).
        Defaults to the working resolution if H and W are omitted.
        """
        target_H = self.H_work if H is None else H
        target_W = self.W_work if W is None else W

        x_pixels = torch.clamp((self.coords[:, :, 0] * target_W).long(), 0, target_W - 1)
        y_pixels = torch.clamp((self.coords[:, :, 1] * target_H).long(), 0, target_H - 1)

        flat_indices = y_pixels * target_W + x_pixels
        num_pixels = target_H * target_W

        flat_masks = torch.zeros(self.N, num_pixels, device=self.device)
        src_ones = torch.ones_like(flat_indices, dtype=torch.float32)
        flat_masks.scatter_(1, flat_indices, src_ones)

        return flat_masks.view(self.N, target_H, target_W)

    def sample_image_values(self, display_image, fill_value=0):
        """
        Samples values from an image at the display resolution at probed locations,
        and returns a downsampled image at the working resolution containing those values.

        Args:
            display_image (Tensor): High-res image of shape (H_disp, W_disp) or (C, H_disp, W_disp).
            fill_value (int or float): Background value for unprobed pixels in the working image.

        Returns:
            working_image (Tensor): Downsampled image of shape (H_work, W_work) or (C, H_work, W_work).
        """
        if isinstance(display_image, torch.Tensor):
            img = display_image.to(self.device)
        else:
            img = torch.tensor(display_image, device=self.device)

        # 1. Determine spatial mapping to display grid
        if img.ndim == 2:
            H_disp, W_disp = img.shape
            is_multichannel = False
        elif img.ndim == 3:
            C, H_disp, W_disp = img.shape
            is_multichannel = True
        else:
            raise ValueError(f"Expected 2D or 3D image tensor, got shape {img.shape}")

        # Compute display pixel coordinates using normalized points
        x_disp = torch.clamp((self.coords[:, :, 0] * W_disp).long(), 0, W_disp - 1)
        y_disp = torch.clamp((self.coords[:, :, 1] * H_disp).long(), 0, H_disp - 1)

        # 2. Extract values from display image at probe locations
        if is_multichannel:
            # Extracted shape: (C, N, order)
            sampled_values = img[:, y_disp, x_disp]
            # Construct working canvas: (C, H_work, W_work)
            working_image = torch.full(
                (C, self.H_work, self.W_work),
                fill_value,
                dtype=img.dtype,
                device=self.device
            )
            # Scatter sampled values onto their corresponding working grid locations
            working_image[:, self.y_work, self.x_work] = sampled_values
        else:
            # Extracted shape: (N, order)
            sampled_values = img[y_disp, x_disp]
            # Construct working canvas: (H_work, W_work)
            working_image = torch.full(
                (self.H_work, self.W_work),
                fill_value,
                dtype=img.dtype,
                device=self.device
            )
            # Scatter sampled values onto their corresponding working grid locations
            working_image[self.y_work, self.x_work] = sampled_values

        return working_image

    def plot_probe(self, image, probe_idx=0, radius=8, color='red', alpha=0.8, ax=None, plain=True):
        """
        Overlays points for a single probe onto an image.

        Args:
            image (Tensor or ndarray): Input image to plot.
            probe_idx (int): Index of the probe to overlay.
            radius (float): Size radius for scatter points.
            color (str): Scatter point color.
            alpha (float): Transparency level of scatter points.
            ax (Axes, optional): Pre-existing Matplotlib axes object.
            plain (bool): If True, plots without titles, legend, axis marks, or padding.
                          If False, plots with standard title, legend, and formatting.
        """
        if isinstance(image, torch.Tensor):
            if image.ndim == 3 and image.shape[0] in [1, 3, 4]:
                img_np = image.detach().cpu().permute(1, 2, 0).numpy()
                if img_np.shape[2] == 1:
                    img_np = img_np.squeeze(-1)
            else:
                img_np = image.detach().cpu().numpy()
        else:
            img_np = image

        img_H, img_W = img_np.shape[:2]
        probe_coords = self.coords[probe_idx].detach().cpu()

        x_pixels = probe_coords[:, 0] * img_W
        y_pixels = probe_coords[:, 1] * img_H

        if ax is None:
            fig, ax = plt.subplots(figsize=(8, 8))
        else:
            fig = ax.get_figure()

        cmap = 'gray' if img_np.ndim == 2 else None
        ax.imshow(img_np, cmap=cmap)
        ax.scatter(
            x_pixels,
            y_pixels,
            s=radius**2,
            c=color,
            edgecolors='white',
            linewidths=1.5,
            alpha=alpha,
            label=f"Probe #{probe_idx}"
        )

        ax.axis('off')

        if plain:
            # Strip all padding/margins and titles for clean saving
            ax.set_title("")
            fig.subplots_adjust(left=0, right=1, bottom=0, top=1, wspace=0, hspace=0)
        else:
            # Apply standard embellishments
            ax.set_title(f"Probe Set #{probe_idx} ({self.order} points) [{img_W}x{img_H}]")
            ax.legend(loc='upper right')

        return ax

    def __repr__(self):
        return (f"ProbeSet(N={self.N}, order={self.order}, "
                f"working=({self.H_work}, {self.W_work}), "
                f"display=({self.H_disp}, {self.W_disp}))")


# ============================================================================
# Regularization Loss Functions
# ============================================================================

class LaplacianSmoothnessLoss(nn.Module):
    """
    Calculates the 'smoothness' of a 2D map by penalizing the 
    squared differences between adjacent pixels.
    
    Equivalent to the term x^T L x (Dirichlet energy) on a grid graph.
    """
    def __init__(self, reduction='mean'):
        super().__init__()
        self.reduction = reduction

    def forward(self, map_tensor):
        """
        Args:
            map_tensor: Input tensor of shape (Batch, Channels, Height, Width)
                        Usually the Uncertainty Map or Logits.
        """
        # 1. Compute differences between horizontal neighbors
        #    (Right pixel - Left pixel)
        diff_x = map_tensor[:, :, :, 1:] - map_tensor[:, :, :, :-1]
        
        # 2. Compute differences between vertical neighbors
        #    (Bottom pixel - Top pixel)
        diff_y = map_tensor[:, :, 1:, :] - map_tensor[:, :, :-1, :]
        
        # 3. Square the differences (L2 norm of the gradient)
        loss_x = diff_x ** 2
        loss_y = diff_y ** 2
        
        # 4. Combine and reduce
        if self.reduction == 'mean':
            return loss_x.mean() + loss_y.mean()
        elif self.reduction == 'sum':
            return loss_x.sum() + loss_y.sum()
        else:
            return loss_x, loss_y


class SpatialConcentrationLoss(nn.Module):
    """
    Penalizes the spatial variance of maps.
    Forces each map to concentrate its mass around a single centroid.
    """
    def __init__(self):
        super().__init__()

    def forward(self, maps):
        """
        Args:
            maps: (Batch, K, H, W). 
                  Should be non-negative (e.g. passed through Softmax or ReLU).
        """
        batch_size, K, H, W = maps.shape
        device = maps.device

        # 1. Create coordinate grids
        # Normalized coordinates [-1, 1] usually work better for optimization stability
        y_coords = torch.linspace(-1, 1, H, device=device).view(1, 1, H, 1)
        x_coords = torch.linspace(-1, 1, W, device=device).view(1, 1, 1, W)
        
        # Expand grids to match batch size: (B, K, H, W)
        # Note: We don't allocate new memory, just broadcast
        x_grid = x_coords.expand(batch_size, K, H, W)
        y_grid = y_coords.expand(batch_size, K, H, W)

        # 2. Normalize maps to be spatial Probability Mass Functions (sum=1)
        # Add epsilon to prevent division by zero for empty maps
        map_sums = maps.sum(dim=(2, 3), keepdim=True) + 1e-6
        spatial_probs = maps / map_sums

        # 3. Calculate Center of Mass (Expected Value of X and Y)
        # Sum over H, W
        center_x = (spatial_probs * x_grid).sum(dim=(2, 3), keepdim=True)
        center_y = (spatial_probs * y_grid).sum(dim=(2, 3), keepdim=True)

        # 4. Calculate Variance (Expected Squared Distance from Center)
        # (x - mu_x)^2 + (y - mu_y)^2
        dist_sq_x = (x_grid - center_x) ** 2
        dist_sq_y = (y_grid - center_y) ** 2
        
        # Weighted sum of squared distances
        variance = (spatial_probs * (dist_sq_x + dist_sq_y)).sum(dim=(2, 3))

        # 5. Return mean loss over the batch and K segments
        return variance.mean()


# ============================================================================
# Comparison and Similarity Functions
# ============================================================================

def objectwise_similarity(learned_map, truth_map, threshold_ratio=1.0):
    """
    Computes the object-wise cosine similarity between a learned map and a ground truth map,
    weighted by the pixel overlap between segments.
    
    Args:
        learned_map (Tensor): Shape (K_L, H, W).
        truth_map (Tensor): Shape (K_T, H, W).
        threshold_ratio (float): Multiplier for the 1/K threshold.
        
    Returns:
        similarity_scores (Tensor): Shape (K_L,). The weighted average similarity 
                                    for each learned segment.
    """
    # 1. Get Shapes and Flatten
    K_L, H, W = learned_map.shape
    K_T = truth_map.shape[0]
    
    flat_L = learned_map.reshape(K_L, -1)
    flat_T = truth_map.reshape(K_T, -1)
    
    # 2. Thresholding (Active Pixels)
    thresh_L = (1.0 / K_L) * threshold_ratio
    thresh_T = (1.0 / K_T) * threshold_ratio
    
    active_L = (flat_L > thresh_L).float()
    active_T = (flat_T > thresh_T).float()
    
    # 3. Calculate Weights (Pixel Overlap Counts)
    # Matrix Mult: (K_L, N) @ (N, K_T) -> (K_L, K_T)
    # Entry [i, j] is exactly the number of pixels shared by Learned_i and Truth_j
    weights = torch.mm(active_L, active_T.t())
    
    # 4. Compute All-Pairs Cosine Similarity
    # Normalize vectors
    norm_L = F.normalize(flat_L, p=2, dim=1)
    norm_T = F.normalize(flat_T, p=2, dim=1)
    
    # Similarity Matrix: (K_L, K_T)
    # Entry [i, j] is the cosine similarity between Learned_i and Truth_j
    similarities = torch.mm(norm_L, norm_T.t())
    
    # 5. Compute Weighted Average
    # We want: Sum(Sim_ij * Weight_ij) / Sum(Weight_ij) for each row i
    
    # Numerator: Weighted sum of similarities
    weighted_sum = (similarities * weights).sum(dim=1) # Shape (K_L,)
    
    # Denominator: Total weight (Total overlapping pixels for this learned segment)
    total_weights = weights.sum(dim=1) # Shape (K_L,)
    
    # 6. Safe Division
    # Avoid division by zero for learned segments that have NO overlap with truth
    # We set their score to 0.0
    scores = torch.zeros_like(weighted_sum)
    mask = total_weights > 0
    
    scores[mask] = weighted_sum[mask] / total_weights[mask]
    
    return scores
