"""
Expected Object Counts Module

This module contains classes and functions for probabilistic segmentation 
and object counting from the expected_object_count_v01.ipynb notebook.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import math
import base64
import json
from torch.distributions.dirichlet import Dirichlet
from torch.optim import Optimizer
from torch.nn import Module, Parameter


# ============================================================================
# Probabilistic Segmentation Classes and Functions
# ============================================================================

class ProbabilisticSegmentation():
    def __init__(self, probability_map=None, dimensions=None, label_map = None):
        num_provided_args = sum([arg is not None for arg in [dimensions, probability_map, label_map]])
        if num_provided_args != 1:
            raise ValueError("Exactly one of 'dimensions', 'probability_map', or 'label_map' must be provided.")
        if dimensions is not None:
            self.K, self.H, self.W = dimensions
            self.probability_map = torch.ones(dimensions)/self.K 
        if probability_map is not None:
            self.check_probability_map(probability_map)
            self.K, self.H, self.W = probability_map.shape
            self.probability_map = probability_map
        if label_map is not None:
            self.probability_map = self.probability_map_from_label_map(label_map)
            self.check_probability_map()
            self.K, self.H, self.W = self.probability_map.shape

    def check_probability_map(self, probability_map=None):
        if probability_map is None:
            probability_map = self.probability_map
        if not (probability_map >= 0).all():
            raise ValueError("All values in 'probability_map' must be non-negative.")
        if not torch.isclose(probability_map.sum(dim=0), torch.ones(probability_map.shape[1], probability_map.shape[2], device = probability_map.device)).all():
            raise ValueError("The sum of probabilities along dimension 0 must be equal to 1 for each pixel.")
        else:
            print("Probability map is valid.")

    def probability_map_from_label_map(self, label_map):
        ##image dimensions
        H,W = label_map.shape
        ##find the unique labels
        unique_labels = torch.unique(label_map)
        K = len(unique_labels)
        probability_map = torch.zeros((K, H, W))
        for i,k in enumerate(unique_labels):
            probability_map[i] = (label_map == k) 
        return probability_map

    def pixel_comembership(self):
        pm = self.probability_map.flatten(1) ##K x HW
        return pm.T @ pm ##HW x HW

    def probability_map_to_string(self):
        """
        Converts a PyTorch tensor (probability map) into a portable JSON string.
        
        Args:
            tensor (Tensor): The input probability map.
            
        Returns:
            str: A JSON string containing shape, dtype, and base64-encoded data.
        """
        # 1. Move to CPU and convert to Numpy
        # We must detach if it requires grad, and move to CPU to convert to numpy
        np_array = self.probability_map.detach().cpu().numpy()
        
        # 2. Serialize the binary data
        # tobytes() gets the raw bits. b64encode converts those bits to ASCII bytes.
        # decode('utf-8') turns those ASCII bytes into a standard Python string.
        b64_data = base64.b64encode(np_array.tobytes()).decode('utf-8')
        
        # 3. Create a dictionary with necessary metadata
        # We need the dtype and shape to reconstruct it correctly later.
        payload = {
            "dtype": str(np_array.dtype),
            "shape": np_array.shape,
            "data": b64_data
        }
        
        # 4. Convert dictionary to JSON string
        return json.dumps(payload)


def dirichlet_probability_map(K, H, W, alpha=20.):
    alpha = torch.tensor([alpha]*K)
    dist = Dirichlet(alpha)
    probability_map = dist.sample((W,H)).transpose(0,2)
    return probability_map

    

def string_to_probability_map(s):
    """
    Reconstructs a PyTorch tensor from the string generated by `probability_map_to_string`.
    
    Args:
        s (str): The JSON string.
        
    Returns:
        Tensor: The reconstructed PyTorch tensor.
    """
    # 1. Parse the JSON string
    payload = json.loads(s)
    
    # 2. Extract metadata
    dtype_name = payload['dtype']
    shape = payload['shape']
    b64_data = payload['data']
    
    # 3. Decode the binary data
    # Convert string back to bytes
    raw_bytes = base64.b64decode(b64_data)
    
    # 4. Reconstruct Numpy Array
    # frombuffer interprets the raw bytes as numbers of the specified dtype
    np_array = np.frombuffer(raw_bytes, dtype=dtype_name)
    
    # 5. Reshape and Convert to Torch
    np_array = np_array.reshape(shape)
    
    # We create a copy to avoid "The given NumPy array is not writeable" warnings 
    # that can occur with read-only buffers from strings.
    tensor = torch.from_numpy(np_array.copy())
    
    return tensor    


# ============================================================================
# Object Counting Network
# ============================================================================

class ExpectedObjectCountNet(nn.Module):
    def __init__(self, probability_map):
        super(ExpectedObjectCountNet, self).__init__()
        self.probability_map = nn.Parameter(probability_map)
        self.K = self.probability_map.shape[0]
        self.H = self.probability_map.shape[1]
        self.W = self.probability_map.shape[2]
        
    def _expected_object_count(self, probes):
        '''
        probes: (B, H, W), B binary probes of size H x W
        '''
        B,H,W = probes.shape
        pseg = self.probability_map #(K, H, W)
        wpseg = torch.einsum('BHW, KHW->BKHW', probes, pseg) # (B, K, H, W)
        prob_seg_not_sampled = 1 - wpseg # (B, K, H, W)
        prob_never_picked = prob_seg_not_sampled.prod(dim=-1).prod(dim=-1) # (B, K)
        expected_object_count = torch.sum(1-prob_never_picked, dim=1) # (B)
        return expected_object_count 

    def forward(self, probes):
        return self._expected_object_count(probes)

    def train(self, probes, count_data, lr=10., laplacian_weight=5., spatial_concentration_weight=1., number_of_epochs=2000, print_progress=False):
        ##instantiate a loss function and optimizer
        # from vseg.src.vseg.models import ExpGradient
        optimizer = ExpGradient(self.parameters(), lr=lr)
        criterion = nn.MSELoss(reduction='mean')
        lps = LaplacianSmoothnessLoss()
        var = SpatialConcentrationLoss()

        ##train the network, saving the loss history
        loss_history = []
        for epoch in range(number_of_epochs):
            optimizer.zero_grad()
            pred = self.forward(probes)
            loss = criterion(pred, count_data)
            energy = lps(self.probability_map[np.newaxis,...])
            fogginess = var(self.probability_map[np.newaxis,...])
            total_loss = loss*1. + energy*laplacian_weight + fogginess*spatial_concentration_weight
            loss_history.append(total_loss.item())
            total_loss.backward()
            optimizer.step()
            if print_progress:
                print(f'Epoch {epoch}, loss : {loss.item():.9f}, energy: {energy.item():.9f}, fogginess: {fogginess.item():.9f}')   
        if print_progress:
            print('Done')
        return loss_history

# ============================================================================
# Target hits network
# ============================================================================

class TargetHitsNet(nn.Module):
    """Directly optimizes probability logits for an h x w image grid across k segments.

    Exponentiated Gradient Descent is natively implemented by optimizing logits 'w'
    with standard SGD, as Softmax(w) mirror-descents on p.
    """

    def __init__(self, height: int, width: int, num_segments: int):
            super().__init__()
            self.height = height
            self.width = width
            self.num_segments = num_segments

            # Initialize with small random values from standard normal: N(0, 0.01^2)
            self.logits = nn.Parameter(
                0.01
                * torch.randn(
                    num_segments, height, width, dtype=torch.float32
                )
            )

    def get_probabilities(self) -> torch.Tensor:
        """Returns normalized segment probabilities p_v(x_j) of shape (k, h, w)."""
        return torch.softmax(self.logits, dim=0)

    def forward(
        self, coords: torch.Tensor, target_segment: int
    ) -> torch.Tensor:
        """Args:

        coords: LongTensor of shape (B, n, 2) containing (y, x) pixel
        coordinates. target_segment: Index v of the segment of interest.

        Returns:
            p_v: Tensor of shape (B, n) with p_v(x_j) for sampled pixels.
        """
        probs = self.get_probabilities()[target_segment]  # Shape (h, w)

        # Gather p_v(x_j) for each sampled coordinate (y, x)
        xs = coords[..., 0]
        ys = coords[..., 1]
        p_v = probs[ys, xs]  # Shape (B, n)
        return p_v



# ============================================================================
# Regularization and Loss Functions
# ============================================================================

class PoissonBinomialPMF(nn.Module):
    """Computes P(R_v = r) for Poisson Binomial Distribution using dynamic programming.

    Given probabilities p of shape (batch_size, n), this computes the log-likelihood
    of observing exactly 'r' hits out of 'n' samples.
    """

    def __init__(self):
        super().__init__()

    def forward(self, p: torch.Tensor, r: torch.Tensor) -> torch.Tensor:
        """Args:

        p: Tensor of shape (B, n) containing p_v(x_j) probabilities.
        r: Tensor of shape (B,) containing observed target segment counts.

        Returns:
            log_prob: Tensor of shape (B,) containing log P(R_v = r).
        """
        B, n = p.shape

        # dp[i][j] = P(j hits using first i pixels)
        # We compute this in log-space or probability space; using DP table:
        dp = torch.zeros(B, n + 1, device=p.device, dtype=p.dtype)
        dp[:, 0] = 1.0  # Base case: 0 pixels sampled -> 0 hits with probability 1

        for i in range(n):
            p_i = p[:, i : i + 1]  # Shape (B, 1)
            dp_next = torch.zeros_like(dp)

            # 0 hits at step i+1: previous 0 hits AND pixel i is not target
            dp_next[:, 0] = dp[:, 0] * (1.0 - p_i.squeeze(-1))

            # k hits at step i+1: (k hits & not target) OR (k-1 hits & target)
            dp_next[:, 1:] = dp[:, 1:] * (1.0 - p_i) + dp[:, :-1] * p_i

            dp = dp_next

        # Gather probability corresponding to observed r for each batch item
        batch_indices = torch.arange(B, device=p.device)
        prob_r = dp[batch_indices, r]

        # Numerical stability clamp
        prob_r = torch.clamp(prob_r, min=1e-12)
        return torch.log(prob_r)


class LaplacianSmoothnessLoss(nn.Module):
    """
    Calculates the 'smoothness' of a 2D map by penalizing the 
    squared differences between adjacent pixels.
    
    Equivalent to the term x^T L x (Dirichlet energy) on a grid graph.
    """
    def __init__(self, reduction='mean'):
        super().__init__()
        self.reduction = reduction

    def forward(self, map_tensor):
        """
        Args:
            map_tensor: Input tensor of shape (Batch, Channels, Height, Width)
                        Usually the Uncertainty Map or Logits.
        """
        # 1. Compute differences between horizontal neighbors
        #    (Right pixel - Left pixel)
        diff_x = map_tensor[:, :, :, 1:] - map_tensor[:, :, :, :-1]
        
        # 2. Compute differences between vertical neighbors
        #    (Bottom pixel - Top pixel)
        diff_y = map_tensor[:, :, 1:, :] - map_tensor[:, :, :-1, :]
        
        # 3. Square the differences (L2 norm of the gradient)
        loss_x = diff_x ** 2
        loss_y = diff_y ** 2
        
        # 4. Combine and reduce
        if self.reduction == 'mean':
            return loss_x.mean() + loss_y.mean()
        elif self.reduction == 'sum':
            return loss_x.sum() + loss_y.sum()
        else:
            return loss_x, loss_y


class SpatialConcentrationLoss(nn.Module):
    """
    Penalizes the spatial variance of maps.
    Forces each map to concentrate its mass around a single centroid.
    """
    def __init__(self):
        super().__init__()

    def forward(self, maps):
        """
        Args:
            maps: (Batch, K, H, W). 
                  Should be non-negative (e.g. passed through Softmax or ReLU).
        """
        batch_size, K, H, W = maps.shape
        device = maps.device

        # 1. Create coordinate grids
        # Normalized coordinates [-1, 1] usually work better for optimization stability
        y_coords = torch.linspace(-1, 1, H, device=device).view(1, 1, H, 1)
        x_coords = torch.linspace(-1, 1, W, device=device).view(1, 1, 1, W)
        
        # Expand grids to match batch size: (B, K, H, W)
        # Note: We don't allocate new memory, just broadcast
        x_grid = x_coords.expand(batch_size, K, H, W)
        y_grid = y_coords.expand(batch_size, K, H, W)

        # 2. Normalize maps to be spatial Probability Mass Functions (sum=1)
        # Add epsilon to prevent division by zero for empty maps
        map_sums = maps.sum(dim=(2, 3), keepdim=True) + 1e-6
        spatial_probs = maps / map_sums

        # 3. Calculate Center of Mass (Expected Value of X and Y)
        # Sum over H, W
        center_x = (spatial_probs * x_grid).sum(dim=(2, 3), keepdim=True)
        center_y = (spatial_probs * y_grid).sum(dim=(2, 3), keepdim=True)

        # 4. Calculate Variance (Expected Squared Distance from Center)
        # (x - mu_x)^2 + (y - mu_y)^2
        dist_sq_x = (x_grid - center_x) ** 2
        dist_sq_y = (y_grid - center_y) ** 2
        
        # Weighted sum of squared distances
        variance = (spatial_probs * (dist_sq_x + dist_sq_y)).sum(dim=(2, 3))

        # 5. Return mean loss over the batch and K segments
        return variance.mean()


# ============================================================================
# Comparison and Similarity Functions
# ============================================================================

def objectwise_similarity(learned_map, truth_map, threshold_ratio=1.0):
    """
    Computes the object-wise cosine similarity between a learned map and a ground truth map,
    weighted by the pixel overlap between segments.
    
    Args:
        learned_map (Tensor): Shape (K_L, H, W).
        truth_map (Tensor): Shape (K_T, H, W).
        threshold_ratio (float): Multiplier for the 1/K threshold.
        
    Returns:
        similarity_scores (Tensor): Shape (K_L,). The weighted average similarity 
                                    for each learned segment.
    """
    # 1. Get Shapes and Flatten
    K_L, H, W = learned_map.shape
    K_T = truth_map.shape[0]
    
    flat_L = learned_map.reshape(K_L, -1)
    flat_T = truth_map.reshape(K_T, -1)
    
    # 2. Thresholding (Active Pixels)
    thresh_L = (1.0 / K_L) * threshold_ratio
    thresh_T = (1.0 / K_T) * threshold_ratio
    
    active_L = (flat_L > thresh_L).float()
    active_T = (flat_T > thresh_T).float()
    
    # 3. Calculate Weights (Pixel Overlap Counts)
    # Matrix Mult: (K_L, N) @ (N, K_T) -> (K_L, K_T)
    # Entry [i, j] is exactly the number of pixels shared by Learned_i and Truth_j
    weights = torch.mm(active_L, active_T.t())
    
    # 4. Compute All-Pairs Cosine Similarity
    # Normalize vectors
    norm_L = F.normalize(flat_L, p=2, dim=1)
    norm_T = F.normalize(flat_T, p=2, dim=1)
    
    # Similarity Matrix: (K_L, K_T)
    # Entry [i, j] is the cosine similarity between Learned_i and Truth_j
    similarities = torch.mm(norm_L, norm_T.t())
    
    # 5. Compute Weighted Average
    # We want: Sum(Sim_ij * Weight_ij) / Sum(Weight_ij) for each row i
    
    # Numerator: Weighted sum of similarities
    weighted_sum = (similarities * weights).sum(dim=1) # Shape (K_L,)
    
    # Denominator: Total weight (Total overlapping pixels for this learned segment)
    total_weights = weights.sum(dim=1) # Shape (K_L,)
    
    # 6. Safe Division
    # Avoid division by zero for learned segments that have NO overlap with truth
    # We set their score to 0.0
    scores = torch.zeros_like(weighted_sum)
    mask = total_weights > 0


# exponentiated gradient descent
class ExpGradient(Optimizer):
    r'''Exponentiated gradient descent optimizer.

    The class ``ExpGradient`` is a subclass of torch.Optimizer. The gradient
    step is

    .. math::

        x_i = x_i \exp\left( -\lambda \nabla L \right) \quad \text{and} 
        \quad x_i = \frac{x_i}{\sum_k x_k}
    
                
    where :math:`\lambda` is the learning rate and :math:`L` is the loss 
    function.

    Parameters
    ----------
    params : iterable
        Iterable of params to optimize or dicts defining param groups.
    lr : float
        Learning rate (default: 1e-3).


    .. Note:: 

    This implementation authored by Jonathan Vacher, 2021
    
    The exponentiated Gradient descent is introduced in 

        Kivinen J, Warmuth MK. Exponentiated gradient versus gradient 
        descent for linear predictors. Information and computation. 1997;
        132(1):1–63.

    
    '''
    def __init__(self, params, lr=1e-3):
        if lr <= 0.0:
            raise ValueError("Invalid learning rate: {}".format(lr))
        defaults = dict(lr=lr)
        super(ExpGradient, self).__init__(params, defaults)

    def step(self, closure=None):
        '''Performs a single optimization step.
        
        :closure (callable, optional): A closure that reevaluates the model
        	and returns the loss.
        '''
        loss = None
        if closure is not None:
            loss = closure()

        #step_size = self.defaults['lr']
        for group in self.param_groups:
            lr = group['lr']
            for p in group['params']:
                if p.grad is None:
                    continue
                grad = p.grad.data
                if grad.is_sparse:
                    raise RuntimeError('ExpGradient does not support sparse '
                                        +'gradients.')

                state = self.state[p]

                # State initialization
                if len(state) == 0:
                    state['step'] = 0

                state['step'] += 1

                p.data = p.data*torch.exp(- lr * grad)
                p.data = p.data/p.data.sum(0)

        return loss
